// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package simple

import (
	"github.com/google/wire"
)

// Injectors from injector.go:

// buat func injector
// return-nya adlh dependency terakhir yg diperlukan (dlm kasus ini adlh service), nama func injector kita awali dg Initialize....
// ini mirip sprti Constructor (New....)
// agar injector ini dpt handle error (dampaknya/sehingga provider dpt handle error) maka tambah return value berupa error
// jdkan isError as parameter provider
func InitializedService(isError bool) (*SimpleService, error) {
	simpleRepository := NewSimpleRepository(isError)
	simpleService, err := NewSimpleService(simpleRepository)
	if err != nil {
		return nil, err
	}
	return simpleService, nil
}

// injector
func InitializedDatabaseRepository() *DatabaseRepository {
	databasePostgre := NewDatabasePostgre()
	databaseMysql := NewDatabaseMysql()
	databaseRepository := NewDatabaseRepository(databasePostgre, databaseMysql)
	return databaseRepository
}

// injector foobar
func InitializedFooBarService() *FooBarService {
	fooRepository := NewFooRepository()
	fooService := NewFooService(fooRepository)
	barRepository := NewBarRepository()
	barService := NewBarService(barRepository)
	fooBarService := NewFooBarService(fooService, barService)
	return fooBarService
}

// Jd sekarang jika ada provider yg butuh SayHallo maka akan dikirim (struct as param-nya) adlh SayHalloImp
// injector yg benar
func InitializedHalloService() *HalloService {
	sayHalloImp := NewSayHalloImp()
	halloService := NewHalloService(sayHalloImp)
	return halloService
}

// provider struct
// struct provider kasus ini perlu pointer FooBar
// kita inginkan Foo-nya (lewat "Foo") diinject dan Bar-nya (lewat "Bar") diinject
func InitializedFooBar() *FooBar {
	foo := NewFoo()
	bar := NewBar()
	fooBar := &FooBar{
		Foo: foo,
		Bar: bar,
	}
	return fooBar
}

// injector.go:

// provider set untuk foo
var fooSet = wire.NewSet(NewFooRepository, NewFooService)

// provider set untuk bar
var barSet = wire.NewSet(NewBarRepository, NewBarService)

// buat provider set
var HalloSet = wire.NewSet(
	NewSayHalloImp, wire.Bind(new(SayHallo),

		new(*SayHalloImp)),
)
