// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package simple

import (
	"github.com/google/wire"
	"io"
	"os"
)

// Injectors from injector.go:

// buat func injector
// return-nya adlh dependency terakhir yg diperlukan (dlm kasus ini adlh service), nama func injector kita awali dg Initialize....
// ini mirip sprti Constructor (New....)
// agar injector ini dpt handle error (dampaknya/sehingga provider dpt handle error) maka tambah return value berupa error
// jdkan isError as parameter provider
func InitializedService(isError bool) (*SimpleService, error) {
	simpleRepository := NewSimpleRepository(isError)
	simpleService, err := NewSimpleService(simpleRepository)
	if err != nil {
		return nil, err
	}
	return simpleService, nil
}

// injector
func InitializedDatabaseRepository() *DatabaseRepository {
	databasePostgre := NewDatabasePostgre()
	databaseMysql := NewDatabaseMysql()
	databaseRepository := NewDatabaseRepository(databasePostgre, databaseMysql)
	return databaseRepository
}

// injector foobar
func InitializedFooBarService() *FooBarService {
	fooRepository := NewFooRepository()
	fooService := NewFooService(fooRepository)
	barRepository := NewBarRepository()
	barService := NewBarService(barRepository)
	fooBarService := NewFooBarService(fooService, barService)
	return fooBarService
}

// Jd sekarang jika ada provider yg butuh SayHallo maka akan dikirim (struct as param-nya) adlh SayHalloImp
// injector yg benar
func InitializedHalloService() *HalloService {
	sayHalloImp := NewSayHalloImp()
	halloService := NewHalloService(sayHalloImp)
	return halloService
}

// provider struct
// struct provider kasus ini perlu pointer FooBar
// kita inginkan Foo-nya (lewat "Foo") diinject dan Bar-nya (lewat "Bar") diinject tp kalau malas bisa langsung saja lewat "*"
func InitializedFooBar() *FooBar {
	foo := NewFoo()
	bar := NewBar()
	fooBar := &FooBar{
		Foo: foo,
		Bar: bar,
	}
	return fooBar
}

// we want use fooValue & barValue for value nya, lalu kita ambil menggunakan struct provider dan semuanya diinject (via "*")
func InitializedFooBarUsingValue() *FooBar {
	foo := _wireFooValue
	bar := _wireBarValue
	fooBar := &FooBar{
		Foo: foo,
		Bar: bar,
	}
	return fooBar
}

var (
	_wireFooValue = fooValue
	_wireBarValue = barValue
)

// INTERFACE VALUE
// siapapun yg bth data interface (kasus ini io.Reader mengembalikan interface) maka inject value-nya menggunakan nilai dr yg diinjeck-kan (kasus ini value-nya adlh value yg ada di os.Stdin)
func InitializedReader() io.Reader {
	reader := _wireFileValue
	return reader
}

var (
	_wireFileValue = os.Stdin
)

// STRUCT FIELD PROVIDER
func InitializedConfiguration() *Configuration {
	application := NewApplication()
	configuration := application.Configuration
	return configuration
}

// CLEAN UP FUNC
// return nya adlh Connection & closure func
func InitializedConnection(name string) (*Connection, func()) {
	file, cleanup := NewFile(name)
	connection, cleanup2 := NewConnection(file)
	return connection, func() {
		cleanup2()
		cleanup()
	}
}

// injector.go:

// provider set untuk foo
var fooSet = wire.NewSet(NewFooRepository, NewFooService)

// provider set untuk bar
var barSet = wire.NewSet(NewBarRepository, NewBarService)

// buat provider set
var HalloSet = wire.NewSet(
	NewSayHalloImp, wire.Bind(new(SayHallo),

		new(*SayHalloImp)),
)

// BINDING VALUE
// ex we have
var fooValue = &Foo{}

var barValue = &Bar{}
