openapi: 3.0.3
info:
  title: Rest API Category
  description: Spesification Rest API Category with Golang
  version: 1.0.0
externalDocs:
  description: Lebih lanjut belajar tentang membuat openapi
  url: https://www.youtube.com/watch?v=o5b6TYSNK5c
servers:
  - url: http://localhost:3000/api
paths:
  /categories:
    get:
      security:
        - CategoryAuth: []
      tags:
        - Category API
      summary: List all categories
      description: List all categories
      responses:
        '200':
          description: Success get all categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'
    post:
      security:
        - CategoryAuth: []
      tags:
        - Category API
      summary: create new category
      description: create new category
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrUpdate'
      responses:
        '201':
          description: success create category
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    $ref: '#/components/schemas/Category'
  /category/{categoryId}:
    get:
      security:
        - CategoryAuth: []
      tags:
        - Category API
      summary: Get a category by id
      description: Get a category by id
      parameters:
        - name: categoryId
          in: path
          description: Category id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: success get a category
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    $ref: '#/components/schemas/Category'
    put:
      security:
        - CategoryAuth: []
      tags:
        - Category API
      summary: Update a category by id
      description: Update a category by id
      parameters:
        - name: categoryId
          in: path
          description: Category id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrUpdate'
      responses:
        '200':
          description: success get a category
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    $ref: '#/components/schemas/Category'
    delete:
      security:
        - CategoryAuth: []
      tags:
        - Category API
      summary: Delete a category by id
      description: Delete a category by id
      parameters:
        - name: categoryId
          in: path
          description: Category id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: success get a category
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
components:
  securitySchemes:
    CategoryAuth:
      type: apiKey
      in: header
      name: X-API-KEY
      description: Authentication for Category API
  schemas:
    Category:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
    CreateOrUpdate:
      type: object
      properties:
        name:
          type: string