openapi: 3.0.3
info:
  title: Rest API Category
  description: Spesification Rest API Category with Golang
  version: 1.0.0
externalDocs:
  description: Lebih lanjut belajar tentang membuat openapi
  url: https://www.youtube.com/watch?v=o5b6TYSNK5c
servers:
  - url: http://localhost:3000/api
paths:
  /categories:
    get:
      tags:
        - Category API
      summary: List all categories
      description: List all categories
      responses:
        '200':
          description: Success get all categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'
    post:
      tags:
        - Category API
      summary: create new category
      description: create new category
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: success create category
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    $ref: '#/components/schemas/Category'
  /category/{categoryId}:
    get:
      tags:
        - Category API
      summary: Get a category
      description: Get a category
      parameters: 
        - name: categoryId
          in: path
          description: Category id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: success get a category
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    $ref: '#/components/schemas/Category'
          
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: number
        name:
          type: string